package_host:
  - ffmpeg
  - python3-virtualenv

roles_host:
  - daowolf2000.linux.docker
  - daowolf2000.linux.openwebui
  - daowolf2000.linux.ollama
  - daowolf2000.linux.comfyui

docker_nvidia_ctk_no_cgroups: true

openwebui_path : /opt/apps/openwebui
openwebui_env : |
  # WEBUI_AUTH=False
  # ENABLE_PERSISTENT_CONFIG=False
  ENABLE_WEB_SEARCH=True
  WEB_SEARCH_RESULT_COUNT=5
  # WEB_SEARCH_ENGINE=perplexity
  ENABLE_OLLAMA_API=True
  OLLAMA_BASE_URLS=http://192.168.1.11:11434
  ENABLE_EVALUATION_ARENA_MODELS=False
  ENABLE_MESSAGE_RATING=False
  ENABLE_COMMUNITY_SHARING=False

jupyter_home: /opt/apps/jupyter

ollama_env:
    - OLLAMA_HOST=0.0.0.0:11434
    - OLLAMA_MODELS={{ ollama_models }}
    - OLLAMA_CONTEXT_LENGTH=40960
    - OLLAMA_NOHISTORY=1
    - OLLAMA_FLASH_ATTENTION=1