roles_host:
  - daowolf2000.linux.docker
  - daowolf2000.linux.openwebui
  - daowolf2000.linux.ollama
  # - daowolf2000.linux.jupyter

docker_nvidia_ctk_no_cgroups: true

openwebui_path : /opt/apps/openwebui

ollama_homedir : /opt/apps/ollama
ollama_user_uid: 3000
ollama_user_gid: 3000
ollama_env:
  - OLLAMA_HOST=0.0.0.0:11434
