# Настройка хоста. Роли, которые должны быть применены на конкретном хосте
# описываются в списках {{ roles_group }} и {{ roles_host }}
# Требует указания {{ target }} - цели применения плейбука

- name: Deploy to {{ target }} # noqa syntax-check[specific]
  hosts: "{{ target }}"
  gather_facts: true
  become: true
  vars:
    roles: "{{ roles_group + roles_host | d([]) }}"

  tasks:

    - ansible.builtin.include_role: 
        name: "{{ role_item }}"
      loop: "{{ roles }}"
      loop_control:
        loop_var: role_item
      tags: [ install, update, config, users ]

